apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-wave-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: Description
      value: Example (sync) wave 1
  project: in-cluster
  source:
    path: simplified-waves/waves/wave-0
    repoURL: 'https://github.com/tjungbauer/blog-gitops-app-dependencies'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
