apiVersion: batch/v1
kind: Job
metadata:
  name: wave-0
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: registry.redhat.io/openshift4/ose-cli:latest
        command: ["sleep", "60"]
      restartPolicy: Never
  backoffLimit: 0