apiVersion: batch/v1
kind: Job
metadata:
  name: postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: registry.redhat.io/openshift4/ose-cli:latest
        command: ["sleep", "120"]
      restartPolicy: Never
  backoffLimit: 0